name: ruitian.y pipeline
trigger:
  push:
    notification:
      when: [success, failure]

jobs:
  job_build:
    image: hub.byted.org/codebase/ci_rust:latest
    runs-on:
      cluster:
    steps:
      - id: checkout
        commands:
          - git submodule update --init --recursive || true
      - id: rust-build
        commands:
          - rustc --version || true
          - cargo --version || true
          - cargo build --locked --release