[package]
name = "lazylog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Terminal Log Viewer Framework"
publish = false                               # Don't publish to crates.io

[[bin]]
name = "lazylog"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
lazylog-framework = { path = "../lazylog-framework" }
lazylog-dyeh = { path = "../lazylog-dyeh" }
lazylog-ios = { path = "../lazylog-ios" }
lazylog-android = { path = "../lazylog-android" }
crossterm.workspace = true
dirs.workspace = true
ratatui.workspace = true
signal-hook.workspace = true
unicode-width.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
